# 01 - Preprocesado y Limpieza (Students, columnas en espanol)

Este notebook transforma el dataset Students y renombra las columnas al espanol para que todo el flujo sea mas comprensible.

In [5]:
import re
import pandas as pd
from pathlib import Path

def find_project_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / 'data').exists() and (p / 'reports').exists():
            return p
    raise RuntimeError('No se encontro la raiz del proyecto')

ROOT = find_project_root(Path.cwd().resolve())
print('Project root:', ROOT)

Project root: /home/raul/Documents/courses/unsa/machine-learning

In [6]:
raw_path = ROOT / 'data/raw/students/Students_Performance_dataset.csv'
out_path = ROOT / 'data/processed/students/students_limpio.csv'

df = pd.read_csv(raw_path)
print('Shape original:', df.shape)
df.head(2)

Shape original: (1194, 31)

,University Admission year,Gender,Age,H.S.C passing year,Program,Current Semester,Do you have meritorious scholarship ?,Do you use University transportation?,How many hour do you study daily?,How many times do you seat for study in a day?,...,What is you interested area?,What is your relationship status?,Are you engaged with any co-curriculum activities?,With whom you are living with?,Do you have any health issues?,What was your previous SGPA?,Do you have any physical disabilities?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
0,2018,Male,24,2016,BCSE,12,Yes,No,3,2,...,Data Schince,Single,Yes,Bachelor,No,2.68,No,3.15,75,25000
1,2021,Male,22,2020,BCSE,4,Yes,Yes,3,2,...,Event management,Single,Yes,Family,No,2.68,No,3.15,36,100000

In [7]:
def to_snake(name: str) -> str:
    s = name.strip().lower()
    s = s.replace('?', '').replace('.', '').replace("'", '')
    s = s.replace('&', ' and ').replace('/', ' ')
    s = s.replace('-', ' ').replace(',', ' ')
    s = s.replace('(', ' ').replace(')', ' ')
    s = re.sub(r'\s+', '_', s)
    s = re.sub(r'[^a-z0-9_]', '', s)
    s = re.sub(r'_+', '_', s).strip('_')
    return s

df.columns = [to_snake(c) for c in df.columns]
for c in df.columns:
    if df[c].dtype == 'object':
        df[c] = df[c].astype(str).str.strip()
        df[c] = df[c].replace({'yes':'Yes','no':'No','YES':'Yes','NO':'No'})

numericas = [
    'average_attendance_on_class', 'what_was_your_previous_sgpa', 'what_is_your_current_cgpa',
    'age', 'current_semester', 'how_many_hour_do_you_study_daily',
    'how_many_hour_do_you_spent_daily_in_social_media',
    'how_many_hour_do_you_spent_daily_on_your_skill_development',
    'how_many_credit_did_you_have_completed', 'what_is_your_monthly_family_income',
    'university_admission_year', 'hsc_passing_year'
]
for c in numericas:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors='coerce')

mapa_es = {
    'university_admission_year': 'anio_admision_universidad',
    'gender': 'sexo',
    'age': 'edad',
    'hsc_passing_year': 'anio_aprobacion_hsc',
    'program': 'programa',
    'current_semester': 'semestre_actual',
    'do_you_have_meritorious_scholarship': 'tiene_beca_merito',
    'do_you_use_university_transportation': 'usa_transporte_universidad',
    'how_many_hour_do_you_study_daily': 'horas_estudio_diario',
    'how_many_times_do_you_seat_for_study_in_a_day': 'veces_estudio_por_dia',
    'what_is_your_preferable_learning_mode': 'modo_aprendizaje_preferido',
    'do_you_use_smart_phone': 'usa_smartphone',
    'do_you_have_personal_computer': 'tiene_computadora_personal',
    'how_many_hour_do_you_spent_daily_in_social_media': 'horas_redes_sociales_diario',
    'status_of_your_english_language_proficiency': 'nivel_ingles',
    'average_attendance_on_class': 'asistencia_promedio_clase',
    'did_you_ever_fall_in_probation': 'alguna_vez_probation',
    'did_you_ever_got_suspension': 'alguna_vez_suspension',
    'do_you_attend_in_teacher_consultancy_for_any_kind_of_academical_problems': 'asiste_consultoria_docente',
    'what_are_the_skills_do_you_have': 'habilidades_principales',
    'how_many_hour_do_you_spent_daily_on_your_skill_development': 'horas_desarrollo_habilidades_diario',
    'what_is_you_interested_area': 'area_interes',
    'what_is_your_relationship_status': 'estado_relacion',
    'are_you_engaged_with_any_co_curriculum_activities': 'participa_actividades_cocurriculares',
    'with_whom_you_are_living_with': 'convivencia',
    'do_you_have_any_health_issues': 'tiene_problemas_salud',
    'what_was_your_previous_sgpa': 'sgpa_previo',
    'do_you_have_any_physical_disabilities': 'tiene_discapacidad_fisica',
    'what_is_your_current_cgpa': 'cgpa_actual',
    'how_many_credit_did_you_have_completed': 'creditos_completados',
    'what_is_your_monthly_family_income': 'ingreso_familiar_mensual'
}

df = df.rename(columns=mapa_es)
out_path.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(out_path, index=False)
print('Archivo limpio generado:', out_path)
print('Columnas:', len(df.columns))
df.head(2)

Archivo limpio generado: /home/raul/Documents/courses/unsa/machine-learning/data/processed/students/students_limpio.csv
Columnas: 31

,anio_admision_universidad,sexo,edad,anio_aprobacion_hsc,programa,semestre_actual,tiene_beca_merito,usa_transporte_universidad,horas_estudio_diario,veces_estudio_por_dia,...,area_interes,estado_relacion,participa_actividades_cocurriculares,convivencia,tiene_problemas_salud,sgpa_previo,tiene_discapacidad_fisica,cgpa_actual,creditos_completados,ingreso_familiar_mensual
0,2018,Male,24,2016,BCSE,12,Yes,No,3,2,...,Data Schince,Single,Yes,Bachelor,No,2.68,No,3.15,75,25000
1,2021,Male,22,2020,BCSE,4,Yes,Yes,3,2,...,Event management,Single,Yes,Family,No,2.68,No,3.15,36,100000

In [8]:
q1 = df['edad'].quantile(0.25)
q3 = df['edad'].quantile(0.75)
iqr = q3 - q1
low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr
outliers = ((df['edad'] < low) | (df['edad'] > high)).sum()

print('Nulos totales:', int(df.isna().sum().sum()))
print('Duplicados:', int(df.duplicated().sum()))
print({'q1': q1, 'q3': q3, 'iqr': iqr, 'lim_inf': low, 'lim_sup': high, 'outliers_edad': int(outliers)})

Nulos totales: 2
Duplicados: 0
{'q1': np.float64(20.0), 'q3': np.float64(22.0), 'iqr': np.float64(2.0), 'lim_inf': np.float64(17.0), 'lim_sup': np.float64(25.0), 'outliers_edad': 13}